services:
  - type: web
    name: jeca
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_flask:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0